services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  django-admin:
    build:
      context: ./Admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Admin:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  bulki-bot:
      build:
        context: ./Market
        dockerfile: Dockerfile
      command: python run.py
      depends_on:
        - postgres
      volumes:
        - ./Market:/app


volumes:
  pgdata: