# Generated by Django 4.2.23 on 2025-06-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_client_external_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
