# Generated by Django 4.2.23 on 2025-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_client_address_client_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('item_count', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
